Major changes to DEVise and JavaScreen release scripts.

diff --git a/scripts/release b/scripts/release
--- a/scripts/release
+++ b/scripts/release
@@ -2,7 +2,7 @@
 
 #  ========================================================================
 #  DEVise Data Visualization Software
-#  (c) Copyright 1992-1996
+#  (c) Copyright 2001
 #  By the DEVise Development Group
 #  Madison, Wisconsin
 #  All Rights Reserved.
@@ -12,134 +12,67 @@
 #  or altered in any way without prior permission from the DEVise
 #  Development Group.
 
+#  Release DEVise.
+
 ############################################################
 
 #  $Id$
 
 #  $Log$
-#  Revision 1.1  1998/06/03 21:12:33  wenger
-#  Moved various scripts into the new 'scripts' directory, and 'Bugs' and
-#  'ToDo' into 'design_doc' to clean up the top-level directory; changed
-#  various scripts accordingly; added new 'devise' module in CVS.
-#
-#  Revision 1.21  1998/02/02 18:25:31  wenger
-#  Strings file can now be loaded manually; name of strings file is now
-#  stored in session file; added 'serverExit' command and kill_devised
-#  script to cleanly kill devised; fixed bug 249; more info is now
-#  printed for unrecognized commands.
-#
-#  Revision 1.20  1997/12/12 20:06:30  wenger
-#  Removed devise.tasvir and devise.etk from release script.
-#
-#  Revision 1.19  1997/12/04 20:59:29  wenger
-#  Added rmmem script to release and devise startup scripts.
-#
-#  Revision 1.18  1997/12/01 21:21:01  wenger
-#  Merged the cleanup_1_4_7_br branch through the cleanup_1_4_7_br3 tag
-#  into the trunk.
-#
-#  Revision 1.17  1997/11/12 15:42:25  wenger
-#  Merged the cleanup_1_4_7_br branch through the cleanup_1_4_7_br_2 tag
-#  into the trunk.
-#
-#  Revision 1.16.2.2  1997/11/18 23:07:37  wenger
-#  Fixed paths to devisec and devised scripts.
-#
-#  Revision 1.16.2.1  1997/11/06 17:59:54  wenger
-#  Added scripts for starting up devisec and devised.
-#
-#  Revision 1.16  1997/10/02 18:46:06  wenger
-#  Opening and saving batch-style sessions in back end now fully working;
-#  added tk2ds.tcl script for conversion.
-#
-#  Revision 1.15  1997/07/25 15:37:51  wenger
-#  Added demo startup scripts to repository and release script.
-#
-#  Revision 1.14  1997/06/05 21:18:39  wenger
-#  Added layout manager Tcl/Tk code to release procedure.
-#
-#  Revision 1.13  1997/02/26 16:30:51  wenger
-#  Merged rel_1_3_1 through rel_1_3_3c changes; compiled on Intel/Solaris.
-#
-#  Revision 1.12.4.1  1997/02/20 20:50:23  wenger
-#  Changed mapping to use ShapeAttr4 for line width.
-#
-#  Revision 1.12  1997/01/22 14:40:22  wenger
-#  Added devise.etk to release scripts; removed merged view buttons from
-#  Stack Control dialog.
-#
-#  Revision 1.11  1997/01/13 15:42:43  wenger
-#  Added lib/FSBox.tk to release.
-#
-#  Revision 1.10  1996/12/30 17:50:07  wenger
-#  Got latest sources to compile on Linux; updated Linux dependencies;
-#  changes devise.dali to devise.tasvir in release script.
-#
-#  Revision 1.9  1996/10/17 23:30:01  wenger
-#  Added sample data, session, and schema files to sources; modified
-#  the release script so that these files get installed into the target
-#  directory; added gen_dist script to generate tar files for distribution;
-#  changed /p/devise/dist structure (removed Devise-1.1.8 directories,
-#  since this actually contains whatever is the current version of
-#  Devise); tar file of the dist structure committed to CVS.
-#
-#  Revision 1.8  1996/09/05 20:05:23  wenger
-#  Put the 'public' and 'run' files into CVS; the release script now installs
-#  them.
-#
-#  Revision 1.7  1996/08/14 21:22:33  wenger
-#  Minor dispatcher cleanups, etc.  Fixed release script to release
-#  statically-linked executables for HP and Sun.
-#
-#  Revision 1.6  1996/07/08 14:27:48  jussi
-#  Added multi/disp to the list of executables to be released.
-#
-#  Revision 1.5  1996/05/16 19:39:43  jussi
-#  Added Solaris/Sparc. Added tentative support for AIX.
-#
-#  Revision 1.4  1996/03/24 20:48:08  jussi
-#  Fixed *.txt path.
-#
-#  Revision 1.3  1996/03/24 20:47:16  jussi
-#  Added *.txt to documentation copy command.
-#
-#  Revision 1.2  1996/01/27 00:22:32  jussi
-#  Devise executable is now 'generic', not 'issm'.
-#
-#  Revision 1.1  1996/01/23 22:06:45  jussi
-#  Initial revision.
-#
 
 ############################################################
 
-set files = "solaris/generic/generic solsparc/generic/generic \
-	sun/generic/generic hp/generic/generic \
-	hp/generic/generic.static sun/generic/generic.static \
-        solaris/multi/disp solsparc/multi/disp \
-	sun/multi/disp hp/multi/disp \
-	lib/control.tk doc/userman.ps doc/sysman.ps \
-	doc/Agreement doc/Copyright doc/Disclaimer"
-set target = /p/devise/public
+#-----------------------------------------------------------
+# Get and check command-line arguments.
 
-if ($#argv > 0) then
-  set target = $1
+if ($#argv < 2) then
+  echo "Usage: release <destination> <arch1> [arch2] ..."
+  echo "  Available architectures:"
+  echo "    solaris (Solaris/Intel),"
+  echo "    solsparc (Solaris/SPARC),"
+  echo "    linux (Linux/Intel)"
+  exit 1
 endif
 
+set dest = $1/release
+set arches = ($argv[2-$#argv])
+
+#-----------------------------------------------------------
+# Make sure we have the files we need to do the release.
+
+set files = (lib/control.tk doc/userman.ps doc/sysman.ps \
+    doc/Agreement doc/Copyright doc/Disclaimer)
 foreach file ($files)
-  if ($file == "") then
-    continue
-  endif
   if (! -f $file) then
-    echo File $file missing. Cannot proceed with release procedure.
+    echo "File $file missing."
+    echo "Cannot proceed with release procedure."
     exit 1
   endif
 end
 
-echo You are about to release YOUR copy of Devise to the
-echo general public. The target directory is $target.
+set archfiles = (generic/generic generic/devise generic/deviseb \
+    generic/devised)
+
+foreach arch ($arches)
+  foreach file ($archfiles)
+    if (! -f $arch/$file) then
+      echo "File $arch/$file missing."
+      echo "Cannot proceed with release procedure."
+      exit 1
+    endif
+  end
+end
+
+#-----------------------------------------------------------
+# Confirm that we want to go ahead.
+
 echo ""
-echo The release includes Solaris/Sun/HP/SGI executables,
-echo Tcl/Tk code, and user and other documentation.
+echo "You are about to release YOUR copy of DEVise to the"
+echo "general public. The destination directory is:"
+echo "  $dest"
+echo ""
+echo "The release includes $arches executables,"
+echo "Tcl/Tk code, and user and other documentation."
 echo ""
 echo -n "Are you absolutely sure you want to do this? [N] "
 
@@ -150,172 +83,96 @@ if ($answer != y && $answer != Y) then
 endif
 
 echo ""
-echo Executing release procedures...
-sleep 1
 
+#-----------------------------------------------------------
+# Create bin directories and copy executables.
 
-echo ""
-echo Releasing new copy of generic Devise executables...
-if (! -d $target) then
-  mkdir $target
+echo "Creating bin directories"
+
+if (! -d $dest) then
+  mkdir $dest
 endif
 
-if (! -d $target/sunx86_54) then
-  mkdir $target/sunx86_54
+if (! -e $dest/bin) then
+  ln -s bin_arch/@sys $dest/bin
 endif
-if (! -f $target/sunx86_55) then
-  ln -s sunx86_54 $target/sunx86_55
+
+if (! -d $dest/bin_arch) then
+  mkdir $dest/bin_arch
 endif
-ls -l solaris/generic/generic $target/sunx86_54/devise
-cp -p solaris/generic/generic $target/sunx86_54/devise
 
-if (! -d $target/sun4m_54) then
-  mkdir $target/sun4m_54
-endif
-if (! -f $target/sun4m_55) then
-  ln -s sun4m_54 $target/sun4m_55
-endif
-if (! -f $target/sun4x_55) then
-  ln -s sun4m_55 $target/sun4x_55
-endif
-ls -l solsparc/generic/generic $target/sun4m_54/devise
-cp -p solsparc/generic/generic $target/sun4m_54/devise
+foreach arch ($arches)
+  echo "Releasing DEVise $arch executables"
 
-if (! -d $target/sun4m_412) then
-  mkdir $target/sun4m_412
-endif
-ls -l sun/generic/generic $target/sun4m_412/devise
-cp -p sun/generic/generic $target/sun4m_412/devise
-ls -l sun/generic/generic.static $target/sun4m_412/devise.static
-cp -p sun/generic/generic.static $target/sun4m_412/devise.static
-
-if (! -d $target/hp700_ux90) then
-  mkdir $target/hp700_ux90
-endif
-ls -l hp/generic/generic $target/hp700_ux90/devise
-cp -p hp/generic/generic $target/hp700_ux90/devise
-ls -l hp/generic/generic.static $target/hp700_ux90/devise.static
-cp -p hp/generic/generic.static $target/hp700_ux90/devise.static
-
-#ls -l aix/generic/generic $target/rs_aix32/devise
-#cp -p aix/generic/generic $target/rs_aix32/devise
-
-
-echo ""
-echo Releasing new copy of PVM Devise executables...
-ls -l solaris/multi/disp $target/sunx86_54/multi
-cp -p solaris/multi/disp $target/sunx86_54/multi
-ls -l solsparc/multi/disp $target/sun4m_54/multi
-cp -p solsparc/multi/disp $target/sun4m_54/multi
-ls -l sun/multi/disp $target/sun4m_412/multi
-cp -p sun/multi/disp $target/sun4m_412/multi
-ls -l hp/multi/disp $target/hp700_ux90/multi
-cp -p hp/multi/disp $target/hp700_ux90/multi
-#ls -l aix/multi/disp $target/rs_aix32/multi
-#cp -p aix/multi/disp $target/rs_aix32/multi
-
-
-echo ""
-echo Releasing new Tcl/Tk code...
-if (! -d $target/lib) then
-  mkdir $target/lib
-endif
-cp -p lib/[a-z]* $target/lib
-cp -p lib/[A-Z]*.* $target/lib
-
-if (! -d $target/lib/LM) then
-  mkdir $target/lib/LM
-endif
-cp -p lib/LM/*.tk $target/lib/LM
-
-
-echo ""
-echo Releasing run files...
-
-set run_target = $target/../run
-
-set rundirs = "$run_target/ $run_target/tmp $run_target/work"
-
-foreach dir ($rundirs)
-  if (! -d $dir) then
-    mkdir $dir
+  if ($arch == linux) then
+    set mainbin = i386_linux
+    set otherbins = (i386_linux22 i386_rh61 i386_rh62)
+  else if ($arch == solaris) then
+    set mainbin = sunx86_54
+    set otherbins = (sunx86_55 sunx86_56 sunx86_57)
+  else if ($arch == solsparc) then
+    set mainbin = sun4m_54
+    set otherbins = (sun4m_55 sun4x_55 sun4x_56 sun4x_57)
   endif
+
+  pushd $dest/bin_arch > /dev/null
+
+  if (! -d $mainbin) then
+    mkdir $mainbin
+  endif
+
+  foreach dir ($otherbins)
+    if (! -e $dir) then
+      ln -s $mainbin $dir
+    endif
+  end
+
+  popd > /dev/null
+
+  cp -p $arch/generic/generic $dest/bin_arch/$mainbin/devise
+  cp -p $arch/generic/devise $dest/bin_arch/$mainbin/devisec
+  cp -p $arch/generic/deviseb $dest/bin_arch/$mainbin
+  cp -p $arch/generic/devised $dest/bin_arch/$mainbin
+  chmod a+rz $dest/bin_arch/$mainbin/*
 end
 
-set runfiles = "run_public/devise \
-	run_public/deviseweb run_public/dumpgif.script \
-	run_public/multi run_public/devise.demo \
-	run_public/devise1.3.demo run_public/multi.demo \
-	run_public/multi1.3.demo run_public/tk2ds.tcl  run_public/devisec \
-	run_public/devised run_public/kill_devised2 RTree/src/Progs/rmmem \
-	run_public/devise_ext_script"
+#-----------------------------------------------------------
+# Release the Tcl/Tk (GUI) code.
 
-foreach file ($runfiles)
-  if ($file == "") then
-    continue
+echo ""
+echo "Releasing Tcl/Tk code"
+if (! -d $dest/lib) then
+  mkdir $dest/lib
+endif
+cp -p lib/[a-z]* $dest/lib
+cp -p lib/[A-Z]*.* $dest/lib
+chmod a+r $dest/lib/*
+
+
+#-----------------------------------------------------------
+# Release run files.
+
+echo ""
+echo "Releasing run files"
+if (! -d $dest/run) then
+  mkdir $dest/run
+endif
+cp -p run.new/* $dest/run
+
+#-----------------------------------------------------------
+# Release documentation.
+
+echo ""
+echo "Releasing documentation"
+if (! -d $dest/doc) then
+  mkdir $dest/doc
   endif
-  if (! -f $file) then
-    echo File $file missing. Cannot proceed with release procedure.
-    exit 1
-  else
-    cp -p $file $run_target
-  endif
-end
+cp -p doc/*.ps doc/*.txt $dest/doc
+cp -p doc/Agreement $dest/doc
+cp -p doc/Copyright $dest/doc
+cp -p doc/Disclaimer $dest/doc
 
-set file = compustat.idx
-if (-f $run_target/$file) then
-  rm $run_target/$file
-endif
-ln -s /p/devise/dat/$file $run_target/$file
+#-----------------------------------------------------------
+# Set up public directory.
 
-set file = crsp_dsm94.idx
-if (-f $run_target/$file) then
-  rm $run_target/$file
-endif
-ln -s /p/devise/dat/$file $run_target/$file
-
-set file = devise.rc
-if (-f $run_target/$file) then
-  rm $run_target/$file
-endif
-ln -s $target/$file $run_target/$file
-
-set file = dsi94.dat
-if (-f $run_target/$file) then
-  rm $run_target/$file
-endif
-ln -s /p/devise/dat/$file $run_target/$file
-
-set file = issm.idx
-if (-f $run_target/$file) then
-  rm $run_target/$file
-endif
-ln -s /p/devise/dat/$file $run_target/$file
-
-
-echo ""
-echo Releasing documentation...
-if (! -d $target/doc) then
-  mkdir $target/doc
-endif
-cp -p doc/*.ps doc/*.txt $target/doc
-cp -p doc/Agreement $target/doc
-cp -p doc/Copyright $target/doc
-cp -p doc/Disclaimer $target/doc
-
-
-echo ""
-echo Setting up other files and directories...
-if (! -f $target/bin) then
-  ln -s @sys $target/bin
-endif
-
-tar cv --exclude=CVS public | tar xv --directory=$target/..
-
-cp run_public/devise $target/devisepub
-
-cp public/transcat.tcl $target
-
-
-echo ""
-echo Done!
+tar cv --exclude=CVS public | tar xv --directory=$dest
