Added common root definition and checking for existence of executable.

diff --git a/run/ams b/run/ams
--- a/run/ams
+++ b/run/ams
@@ -1,11 +1,20 @@
 #! /bin/csh -f
 
-setenv DEVISE_DAT /p/devise/dat
-setenv DEVISE_CACHE /p/devise/cache
-setenv DEVISE_SCHEMA /p/devise/schema/schema
-setenv DEVISE_SESSION /p/devise/session
-setenv DEVISE_LIB /p/devise/$USER/lib
-setenv DEVISE_TMP /tmp/$USER-devise-tmp
-setenv DEVISE_WORK /tmp/$USER-devise-work
+setenv DEVISE_ROOT    /p/devise
 
-bin/ams/ams $*
+setenv DEVISE_DAT     $DEVISE_ROOT/dat
+setenv DEVISE_CACHE   $DEVISE_ROOT/cache
+setenv DEVISE_SCHEMA  $DEVISE_ROOT/schema/schema
+setenv DEVISE_SESSION $DEVISE_ROOT/session
+setenv DEVISE_LIB     $DEVISE_ROOT/`whoami`/lib
+setenv DEVISE_TMP     /tmp/`whoami`-devise-tmp
+setenv DEVISE_WORK    /tmp/`whoami`-devise-work
+setenv DEVISE_EXEC    bin/ams/ams
+
+if (! -f $DEVISE_EXEC) then
+  echo "Cannot find Devise executable ($DEVISE_EXEC)."
+  echo "Perhaps you haven't compiled for this platform?"
+  exit 1
+endif
+
+$DEVISE_EXEC $*
